### PR TITLE
FIX: cannot import name 'url_quote' from 'werkzeug.urls'

### PR DESCRIPTION
**Pull request by ilkersigirci**

### CODE REVIEW

**Comment by varunsudarshan** [comment]
Tried to build with this change, Ran into an error.
```
=> ERROR [4/5] RUN pip install  --trusted-host pypi.python.org -r requirements.txt                                         45.4s
------                                                                                                                            
 > [4/5] RUN pip install  --trusted-host pypi.python.org -r requirements.txt:                                                     
7.696 WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f846e1ce880>: Failed to establish a new connection: [Errno -3] Try again')': /simple/flask/                                                                                                
13.20 WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f846e1ce3d0>: Failed to establish a new connection: [Errno -3] Try again')': /simple/flask/
19.21 WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f846e1ce2b0>: Failed to establish a new connection: [Errno -3] Try again')': /simple/flask/
26.22 WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f846e1ceca0>: Failed to establish a new connection: [Errno -3] Try again')': /simple/flask/
35.22 WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f846e1ceaf0>: Failed to establish a new connection: [Errno -3] Try again')': /simple/flask/
40.23 ERROR: Could not find a version that satisfies the requirement Flask==2.2.3 (from versions: none)
40.23 ERROR: No matching distribution found for Flask==2.2.3
------
Dockerfile:9
--------------------
   7 |     COPY requirements.txt .
   8 |     
   9 | >>> RUN pip install  --trusted-host pypi.python.org -r requirements.txt
  10 |     
  11 |     # Copy the current directory contents into the container at /app
--------------------
ERROR: failed to solve: process "/bin/sh -c pip install  --trusted-host pypi.python.org -r requirements.txt" did not complete successfully: exit code: 1
```

**Comment by varunsudarshan** [comment]
Builds with docker build --network=host

**Comment by KaiStarkk** [comment]
Not sure what issue this is referring to. Is the issue on a forked repo? Seems like an unnecessary dependency if it is already building with the current .lock?

**Comment by ilkersigirci** [comment]
@KaiStarkk The issue is, if we don't pin werkzeug dependency, flask will get the provided error and the app won't start. Anyone can reproduce this issue if they rebuild Docker image.

**Comment by KaiStarkk** [comment]
@ilkersigirci thanks for the fix! Apologies for the delay.

**Pull request merged**
